adding temperature reading
adafruit/Adafruit_CircuitPython_MLX90393 pull request #35
Opened 2023-02-16 13:19 UTC by jposada202020

PR is to add the ability to read the temperature provided by the sensor. solves #32 

### Dessign Choices

1. I did not include the temperature as a @property as the library is already big, and I do no beleive that the purpose of the sensor is to measure temperature.
2. We could read the 4 values at the same time changing `_CMD_AXIS_ALL` to  = const(0xF) , and give them to the user, however I choose not to, because sensor application. Temeprature will need to read register 0x24 adding time to get the value.
3. Put the temperature reading as a optional for folks that would need it

PR could be test using the following script

```python

# SPDX-FileCopyrightText: 2021 ladyada for Adafruit Industries
# SPDX-License-Identifier: MIT

import time
import board
import adafruit_mlx90393

i2c = board.I2C()  # uses board.SCL and board.SDA
# i2c = board.STEMMA_I2C()  # For using the built-in STEMMA QT connector on a microcontroller
SENSOR = adafruit_mlx90393.MLX90393(i2c, gain=adafruit_mlx90393.GAIN_1X)

while True:
    MX, MY, MZ = SENSOR.magnetic
    print("X: {} uT".format(MX))
    print("Y: {} uT".format(MY))
    print("Z: {} uT".format(MZ))

    # Display the status field if an error occured, etc.
    if SENSOR.last_status > adafruit_mlx90393.STATUS_OK:
        SENSOR.display_status()
    print("Temperature: {}C".format(SENSOR.read_temp()))
    # Display the status field if an error occured, etc.
    if SENSOR.last_status > adafruit_mlx90393.STATUS_OK:
        SENSOR.display_status()
    time.sleep(1.0)

```

2023-02-16 18:32 UTC, tannewt requested changes
Please make it a property so it is consistent with other libraries. It shouldn't be much bigger as a property.

2023-02-16 18:55 UTC, jposada202020 commented
Will do :). Thanks

2023-02-16 22:26 UTC, jposada202020 commented
Added as a property and included an example to test and further reference

2023-02-17 18:29 UTC, tannewt approved these changes
Thank you!

2023-02-17 18:29 UTC, merged